# -*- coding: utf-8 -*-
"""multiple_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gebmipEdRNzMTD5S0T8DE5qRZrYdK_GB
"""

from google.colab import drive

drive.mount('/content/drive')

#!pip install -U langchain-openai

#!pip install -U crewai crewai-tools openai

!pip install crewai

from google.colab import userdata
import os

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")
os.environ["SERPER_API_KEY"] = userdata.get("SERPER_API_KEY")

print("✅ OpenAI API key loaded:", bool(os.environ["OPENAI_API_KEY"]))
print("✅ Serper API key loaded:", bool(os.environ["SERPER_API_KEY"]))

#!pip install -U crewai crewai-tools langchain-openai

# ============================================================
# CREWAI - GOOGLE COLAB | COMPLETE SINGLE CELL
# ============================================================

import sys
import os

# ------------------------------------------------------------
# 1. Install required packages
# ------------------------------------------------------------

!{sys.executable} -m pip install -q -U crewai crewai-tools


# ------------------------------------------------------------
# 2. Import libraries
# ------------------------------------------------------------

from google.colab import userdata

from crewai import Agent, Task, Crew, Process
from crewai_tools import SerperDevTool


# ------------------------------------------------------------
# 3. Load API keys from Google Colab Secrets
# ------------------------------------------------------------

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")
os.environ["SERPER_API_KEY"] = userdata.get("SERPER_API_KEY")

print("OpenAI key loaded:", bool(os.environ["OPENAI_API_KEY"]))
print("Serper key loaded:", bool(os.environ["SERPER_API_KEY"]))


# ------------------------------------------------------------
# 4. Create Search Tool
# ------------------------------------------------------------

search_tool = SerperDevTool()

print("✅ Serper search tool initialized")


# ------------------------------------------------------------
# 5. Configure LLM
# ------------------------------------------------------------

llm = "openai/gpt-4o-mini"


# ------------------------------------------------------------
# 6. Create Research Agent
# ------------------------------------------------------------

researcher = Agent(
    role="Senior AI Research Analyst",

    goal=(
        "Research and identify the latest developments, trends, "
        "breakthroughs and industry applications in Artificial Intelligence."
    ),

    backstory="""
    You are a senior AI research analyst working at a leading
    technology research organization.

    You specialize in identifying emerging AI technologies,
    analyzing technical developments and converting complex
    information into structured and actionable insights.

    You focus on factual, reliable and well-structured research.
    """,

    llm=llm,

    tools=[search_tool],

    verbose=True,

    allow_delegation=False
)


# ------------------------------------------------------------
# 7. Create Writer Agent
# ------------------------------------------------------------

writer = Agent(
    role="Technology Content Strategist",

    goal=(
        "Transform technical AI research into clear, engaging "
        "and professional technology content."
    ),

    backstory="""
    You are an experienced technology content strategist.

    You specialize in transforming complex AI and software
    engineering concepts into clear, professional and engaging
    content suitable for a technical audience.

    You prioritize accuracy, clarity and professional communication.
    """,

    llm=llm,

    verbose=True,

    allow_delegation=False
)


# ------------------------------------------------------------
# 8. Create Research Task
# ------------------------------------------------------------

task1 = Task(
    description="""
    Conduct a comprehensive analysis of the latest advancements
    in Artificial Intelligence in 2026.

    Research the following areas:

    1. Generative AI
    2. Agentic AI
    3. Multi-agent systems
    4. Large Language Models
    5. Multimodal AI
    6. AI infrastructure
    7. AI coding systems
    8. Enterprise AI
    9. AI applications across industries
    10. Important technological breakthroughs

    Use the web search tool to gather current information.

    Clearly distinguish factual information from opinions,
    predictions and speculation.

    Do not invent statistics or unsupported claims.
    """,

    expected_output="""
    A structured research report containing:

    - Major AI developments in 2026
    - Key technologies
    - Generative AI developments
    - Agentic AI developments
    - Multi-agent systems
    - Large Language Models
    - Multimodal AI
    - AI infrastructure
    - Enterprise applications
    - Important examples
    - Relevant sources
    """,

    agent=researcher
)


# ------------------------------------------------------------
# 9. Create Writing Task
# ------------------------------------------------------------

task2 = Task(
    description="""
    Using the research produced by the Research Analyst,
    write a professional technology article about the
    latest AI advancements in 2026.

    Requirements:

    - Include a strong title
    - Include an introduction
    - Explain major AI developments
    - Explain Generative AI
    - Explain Agentic AI
    - Explain Multi-agent systems
    - Discuss industry applications
    - Discuss future implications
    - Include a concise conclusion
    - Use professional and natural English
    - Make the content easy to understand
    - Avoid unnecessary technical jargon
    - Do not invent statistics
    - Do not make unsupported claims
    """,

    expected_output="""
    A polished technology article containing:

    - Title
    - Introduction
    - Major AI developments
    - Generative AI
    - Agentic AI
    - Multi-agent systems
    - Industry applications
    - Future implications
    - Conclusion
    """,

    agent=writer,

    context=[task1]
)


# ------------------------------------------------------------
# 10. Create Crew
# ------------------------------------------------------------

crew = Crew(
    agents=[
        researcher,
        writer
    ],

    tasks=[
        task1,
        task2
    ],

    process=Process.sequential,

    verbose=True
)


# ------------------------------------------------------------
# 11. Run CrewAI asynchronously
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("🚀 STARTING CREWAI")
print("=" * 80)
print()

result = await crew.kickoff_async()


# ------------------------------------------------------------
# 12. Display Final Result
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("✅ FINAL RESULT")
print("=" * 80)
print()

print(result)

"""# New Section"""

























