# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tnheg0jrWyD8toLSVcraV4KW1zsh2U8u
"""

from google.colab import drive

drive.mount('/content/drive')

print("Google Drive connected!")

!ls /content/drive/MyDrive

import os
os.environ['OPENROUTER_API_KEY'] = ""

import requests

API_KEY = ""

response = requests.post(
    url="https://openrouter.ai/api/v1/chat/completions",
    headers={
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    },
    json={
        "model": "deepseek/deepseek-r1",
        "messages": [
            {
                "role": "user",
                "content": "What is the meaning of life?"
            }
        ]
    }
)

print("Status Code:", response.status_code)
print(response.json())

response2 = response.json()
print(response2["choices"][0]["message"]["content"])

import requests

API_KEY = ""

url = "https://openrouter.ai/api/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
}

# First API call
response = requests.post(
    url=url,
    headers=headers,
    json={
        "model": "moonshotai/kimi-k2.5",
        "messages": [
            {
                "role": "user",
                "content": "How many r's are in the word 'strawberry'?"
            }
        ],
        "reasoning": {
            "enabled": True
        },
        "max_tokens": 2000
    }
)

if response.status_code != 200:
    print("API Error:", response.status_code)
    print(response.text)

else:
    data = response.json()

    assistant_message = data["choices"][0]["message"]

    messages = [
        {
            "role": "user",
            "content": "How many r's are in the word 'strawberry'?"
        },
        {
            "role": "assistant",
            "content": assistant_message.get("content"),
            "reasoning_details": assistant_message.get("reasoning_details")
        },
        {
            "role": "user",
            "content": "Are you sure? Think carefully."
        }
    ]

    # Second API call
    response2 = requests.post(
        url=url,
        headers=headers,
        json={
            "model": "moonshotai/kimi-k2.5",
            "messages": messages,
            "reasoning": {
                "enabled": True
            },
            "max_tokens": 2000
        }
    )

    if response2.status_code != 200:
        print("Second API Error:", response2.status_code)
        print(response2.text)

    else:
        result = response2.json()

        print("Final Answer:")
        print(result["choices"][0]["message"]["content"])

print(result)

import requests

API_KEY = ""

url = "https://openrouter.ai/api/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
}

# -----------------------------------
# FIRST API CALL
# -----------------------------------

response = requests.post(
    url=url,
    headers=headers,
    json={
        "model": "nvidia/nemotron-3-ultra-550b-a55b:free",
        "messages": [
            {
                "role": "user",
                "content": "How many r's are in the word 'strawberry'?"
            }
        ],
        "reasoning": {
            "enabled": True
        },
        "max_tokens": 1000
    }
)

# Check first response
if response.status_code != 200:
    print("First API Error:")
    print(response.status_code)
    print(response.text)

else:
    data = response.json()

    # Extract assistant message
    assistant_message = data["choices"][0]["message"]

    # -----------------------------------
    # PRESERVE REASONING
    # -----------------------------------

    messages = [
        {
            "role": "user",
            "content": "How many r's are in the word 'strawberry'?"
        },
        {
            "role": "assistant",
            "content": assistant_message.get("content"),
            "reasoning_details": assistant_message.get("reasoning_details")
        },
        {
            "role": "user",
            "content": "Are you sure? Think carefully."
        }
    ]

    # -----------------------------------
    # SECOND API CALL
    # -----------------------------------

    response2 = requests.post(
        url=url,
        headers=headers,
        json={
            "model": "nvidia/nemotron-3-ultra-550b-a55b:free",
            "messages": messages,
            "reasoning": {
                "enabled": True
            },
            "max_tokens": 1000
        }
    )

    # Check second response
    if response2.status_code != 200:
        print("Second API Error:")
        print(response2.status_code)
        print(response2.text)

    else:
        result = response2.json()

        print("Final Answer:")
        print(result["choices"][0]["message"]["content"])

import time

time.sleep(10)  # wait 10 seconds before second request

response2 = requests.post(
    url=url,
    headers=headers,
    json={
        "model": "poolside/laguna-s-2.1:free",
        "messages": messages,
        "reasoning": {
            "enabled": True
        },
        "max_tokens": 500
    }
)

if response2.status_code == 200:
    result = response2.json()

    print("Final Answer:")
    print(result["choices"][0]["message"]["content"])

else:
    print("Second API Error:", response2.status_code)
    print(response2.text)

import requests

API_KEY = ""


response = requests.post(
    "https://openrouter.ai/api/v1/chat/completions",
    headers={
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    },
    json={
        "model": "poolside/laguna-s-2.1:free",
        "messages": [
            {
                "role": "user",
                "content": "How many r's are in the word 'strawberry'?"
            }
        ],
        "max_tokens": 500
    }
)

print("Status Code:", response.status_code)
print("Response:")

if response.status_code == 200:
    data = response.json()
    print(data["choices"][0]["message"]["content"])
else:
    print(response.text)

import requests

API_KEY = ""

url = "https://openrouter.ai/api/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}

# -----------------------------------
# FIRST API CALL
# -----------------------------------

response = requests.post(
    url=url,
    headers=headers,
    json={
        "model": "nvidia/nemotron-3-super-120b-a12b:free",
        "messages": [
            {
                "role": "user",
                "content": "How many r's are in the word 'strawberry'?"
            }
        ],
        "reasoning": {
            "enabled": True
        },
        "max_tokens": 500
    }
)

# Check first response
if response.status_code != 200:
    print("First API Error:", response.status_code)
    print(response.text)

else:
    data = response.json()

    # Extract assistant message
    assistant_message = data["choices"][0]["message"]

    # -----------------------------------
    # PRESERVE REASONING DETAILS
    # -----------------------------------

    messages = [
        {
            "role": "user",
            "content": "How many r's are in the word 'strawberry'?"
        },
        {
            "role": "assistant",
            "content": assistant_message.get("content"),
            "reasoning_details": assistant_message.get("reasoning_details")
        },
        {
            "role": "user",
            "content": "Are you sure? Think carefully."
        }
    ]

    # -----------------------------------
    # SECOND API CALL
    # -----------------------------------

    response2 = requests.post(
        url=url,
        headers=headers,
        json={
            "model": "nvidia/nemotron-3-super-120b-a12b:free",
            "messages": messages,
            "reasoning": {
                "enabled": True
            },
            "max_tokens": 500
        }
    )

    # Check second response
    if response2.status_code != 200:
        print("Second API Error:", response2.status_code)
        print(response2.text)

    else:
        result = response2.json()

        print("Final Answer:")
        print(result["choices"][0]["message"]["content"])

import requests

API_KEY = ""

url = "https://openrouter.ai/api/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}

# -----------------------------------
# FIRST API CALL
# -----------------------------------

response = requests.post(
    url=url,
    headers=headers,
    json={
        "model": "inclusionai/ling-3.0-flash-sante:free",
        "messages": [
            {
                "role": "user",
                "content": "How many r's are in the word 'strawberry'?"
            }
        ],
        "reasoning": {
            "enabled": True
        },
        "max_tokens": 500
    }
)

# Check first response
if response.status_code != 200:
    print("First API Error:", response.status_code)
    print(response.text)

else:
    data = response.json()

    # Extract assistant message
    assistant_message = data["choices"][0]["message"]

    # -----------------------------------
    # PRESERVE REASONING DETAILS
    # -----------------------------------

    messages = [
        {
            "role": "user",
            "content": "How many r's are in the word 'strawberry'?"
        },
        {
            "role": "assistant",
            "content": assistant_message.get("content"),
            "reasoning_details": assistant_message.get("reasoning_details")
        },
        {
            "role": "user",
            "content": "Are you sure? Think carefully."
        }
    ]

    # -----------------------------------
    # SECOND API CALL
    # -----------------------------------

    response2 = requests.post(
        url=url,
        headers=headers,
        json={
            "model": "inclusionai/ling-3.0-flash-sante:free",
            "messages": messages,
            "reasoning": {
                "enabled": True
            },
            "max_tokens": 500
        }
    )

    # Check second response
    if response2.status_code != 200:
        print("Second API Error:", response2.status_code)
        print(response2.text)

    else:
        result = response2.json()

        print("Final Answer:")
        print(result["choices"][0]["message"]["content"])

import requests

API_KEY = ""

url = "https://openrouter.ai/api/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}

# -----------------------------------
# FIRST API CALL
# -----------------------------------

response = requests.post(
    url=url,
    headers=headers,
    json={
        "model": "google/gemma-4-31b-it:free",
        "messages": [
            {
                "role": "user",
                "content": "How many r's are in the word 'strawberry'?"
            }
        ],
        "reasoning": {
            "enabled": True
        },
        "max_tokens": 500
    }
)

# Check first response
if response.status_code != 200:
    print("First API Error:", response.status_code)
    print(response.text)

else:
    data = response.json()

    # Extract assistant message
    assistant_message = data["choices"][0]["message"]

    # -----------------------------------
    # PRESERVE REASONING DETAILS
    # -----------------------------------

    messages = [
        {
            "role": "user",
            "content": "How many r's are in the word 'strawberry'?"
        },
        {
            "role": "assistant",
            "content": assistant_message.get("content"),
            "reasoning_details": assistant_message.get("reasoning_details")
        },
        {
            "role": "user",
            "content": "Are you sure? Think carefully."
        }
    ]

    # -----------------------------------
    # SECOND API CALL
    # -----------------------------------

    response2 = requests.post(
        url=url,
        headers=headers,
        json={
            "model": "google/gemma-4-31b-it:free",
            "messages": messages,
            "reasoning": {
                "enabled": True
            },
            "max_tokens": 500
        }
    )

    # Check second response
    if response2.status_code != 200:
        print("Second API Error:", response2.status_code)
        print(response2.text)

    else:
        result = response2.json()

        print("Final Answer:")
        print(result["choices"][0]["message"]["content"])



