# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11uyz3vD3G_2ic6fn-V-wOichHgVbtOSz
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import tensorflow as tf
import numpy as np

import tensorflow as tf

df = pd.read_csv("/content/sample_data/tmdb_5000_movies.csv")

df

df.columns

df = df['original_title']

df

movie_name=df.to_list()

tokenizer=tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(movie_name)
seq=tokenizer.texts_to_sequences(movie_name)

seq

tokenizer.word_index

movie_name

x = []
y = []
total_words_dropped = 0

for i in seq:
    if len(i) > 1:
        for index in range(1, len(i)):
            x.append(i[:index])
            y.append(i[index])
    else:
        total_words_dropped += 1

print("Total Single Words Dropped are:", total_words_dropped)

y[:10]

x = tf.keras.preprocessing.sequence.pad_sequences(x)

vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

vocab_size

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, 14),
    tf.keras.layers.LSTM(100, return_sequences=True),
    tf.keras.layers.LSTM(100),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(vocab_size, activation='softmax')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.004),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

x = tf.convert_to_tensor(x)
y = tf.convert_to_tensor(y)

model.fit(x, y, epochs=100)

model.save('nwp.h5')

import os
print("Current working directory:", os.getcwd())

vocab_array = np.array(list(tokenizer.word_index.keys()))

vocab_array

def make_prediction(text, n_words):
    for i in range(n_words):
        text_tokenize = tokenizer.texts_to_sequences([text])
        text_padded = tf.keras.preprocessing.sequence.pad_sequences(text_tokenize, maxlen=14)
        prediction = np.squeeze(np.argmax(model.predict(text_padded), axis=-1))
        prediction = str(vocab_array[prediction - 1])
        print(vocab_array[np.argsort(model.predict(text_padded)) - 1].ravel()[:-3])
        text += " " + prediction
    return text

make_prediction("cloudy", 10)

make_prediction("mars", 10)



